
import React from 'react';
import { Home, Building2, Sparkles, MoveHorizontal, Grid, Hammer, CalendarCheck, CreditCard, Heart, Waves, TreePine, ChefHat, Sofa, BedDouble, Bath } from 'lucide-react';
import { ServiceCardProps, Testimonial, NavLink, ServiceArea, TeamMember, ChecklistRoom } from './types';

export const VIBES = [
  { id: 'fresh', color: '#3b82f6', icon: '❄️', key: 'vibe_fresh', particles: 'sparkle' },
  { id: 'citrus', color: '#facc15', icon: '🍋', key: 'vibe_citrus', particles: 'glow' },
  { id: 'lavender', color: '#a855f7', icon: '🌿', key: 'vibe_lavender', particles: 'leaf' },
  { id: 'eucalyptus', color: '#10b981', icon: '🍃', key: 'vibe_eucalyptus', particles: 'leaf' },
];

export const NAV_LINKS = [
  { href: '#home', key: 'nav_home' },
  { href: '#services', key: 'nav_services' },
  { href: '#about', key: 'nav_about' },
  { href: '#how', key: 'nav_how' },
  { href: '#reviews', key: 'nav_reviews' },
  { href: '#contact', key: 'nav_contact' },
];

export const SERVICES = [
  { id: 'res', icon: <Home className="w-8 h-8" /> },
  { id: 'com', icon: <Building2 className="w-8 h-8" /> },
  { id: 'deep', icon: <Sparkles className="w-8 h-8" /> },
  { id: 'move', icon: <MoveHorizontal className="w-8 h-8" /> },
  { id: 'win', icon: <Grid className="w-8 h-8" /> },
  { id: 'post', icon: <Hammer className="w-8 h-8" /> },
];

export const TESTIMONIALS: Testimonial[] = [
  { id: 1, name: 'Sarah Johnson', location: 'Miami, FL', text: 'Best cleaning service I have ever used. Meticulous!', stars: 5 },
  { id: 2, name: 'Ricardo Silva', location: 'Boston, MA', text: 'The Brazilian touch is real. My house smells amazing.', stars: 5 },
  { id: 3, name: 'Emily Davis', location: 'Jersey City, NJ', text: 'Reliable and professional. Highly recommended!', stars: 5 }
];

export const PROCESS_STEPS = [
  { id: 1, key: 'process1' },
  { id: 2, key: 'process2' },
  { id: 3, key: 'process3' },
];

export const STATS = [
  { id: 'happy', key: 'statsHappy', value: '500+' },
  { id: 'clean', key: 'statsClean', value: '2500+' },
  { id: 'rating', key: 'statsRating', value: '4.9' },
];

export const SERVICE_AREAS: ServiceArea[] = [
  {
    state: 'Florida',
    cities: ['Miami', 'Orlando', 'Tampa', 'Fort Lauderdale', 'Boca Raton']
  },
  {
    state: 'Massachusetts',
    cities: ['Boston', 'Cambridge', 'Worcester', 'Quincy', 'Newton']
  },
  {
    state: 'New Jersey',
    cities: ['Newark', 'Jersey City', 'Princeton', 'Hoboken', 'Trenton']
  }
];

export const TEAM: TeamMember[] = [
  {
    id: 1,
    name: 'Helena Silva',
    role: 'team_1_role',
    specialty: 'team_1_specialty',
    bio: 'team_1_bio',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 2,
    name: 'Ana Costa',
    role: 'team_2_role',
    specialty: 'team_2_specialty',
    bio: 'team_2_bio',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 3,
    name: 'Beatriz Lima',
    role: 'team_3_role',
    specialty: 'team_3_specialty',
    bio: 'team_3_bio',
    image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=800'
  }
];

export const CHECKLIST_ROOMS: ChecklistRoom[] = [
  {
    id: 'kitchen',
    nameKey: 'kitchens',
    items: ['k_1', 'k_2', 'k_3', 'k_4', 'k_5']
  },
  {
    id: 'bathroom',
    nameKey: 'bathrooms',
    items: ['b_1', 'b_2', 'b_3', 'b_4', 'b_5']
  },
  {
    id: 'bedroom',
    nameKey: 'bedrooms',
    items: ['be_1', 'be_2', 'be_3', 'be_4', 'be_5']
  }
];

export const TRANSLATIONS = {
  en: {
    liveActivity: "Live Operations",
    liveMsg: "Teams active in your area",
    lastClean: "Last service completed",
    activeTeams: "Active Teams",
    meetTeam: "Meet the Artisans",
    teamSub: "Behind every Lumina clean is a dedicated professional trained in the 'White-Glove' Brazilian standard.",
    exploreChecklist: "White-Glove Standards",
    checklistDesc: "Select a room to see our 50-point precision protocol.",
    roomProtocol: "Room Protocol",
    scrutinizedMsg: "Every corner scrutinized by our lead supervisor.",
    // Team
    team_1_role: "Senior Lead Pro", team_1_specialty: "Hospitality Specialist", team_1_bio: "15 years of experience bringing the high-end Brazilian standard to American luxury homes.",
    team_2_role: "Sanitization Expert", team_2_specialty: "Clinical Cleaning", team_2_bio: "Obsessive about details. Ana ensures every surface is not just clean, but molecularly pure.",
    team_3_role: "Organization Artist", team_3_specialty: "Closet & Space Layout", team_3_bio: "Beatriz believes that order in the house leads to order in the mind. Her finishing touches are legendary.",
    // Checklist Items
    k_1: "Degrease hood and stovetop", k_2: "Polish stainless steel", k_3: "Inside microwave deep clean", k_4: "Cabinet exterior detail", k_5: "Tile grout scrub",
    b_1: "Mineral deposit removal", b_2: "Mirror streak-free polish", b_3: "Sanitize all high-touch points", b_4: "Floor hand-scrubbing", b_5: "Glass shower door scaling",
    be_1: "Premium bed making", be_2: "Dusting baseboards & crown molding", be_3: "Ventilation grill detailing", be_4: "Under-bed vacuuming", be_5: "Upholstery fluffing",
    // UI
    estimatorTitle: "Custom Quote Engine",
    estimatorSub: "Configure your space with precision for an instant estimate.",
    bedrooms: "Bedrooms",
    suites: "Suites",
    livingRooms: "Living Rooms",
    kitchens: "Kitchens",
    bathrooms: "Bathrooms",
    pool: "Pool Area",
    garden: "Garden/Yard",
    sqft: "Total Area (sq ft)",
    cleaningType: "Cleaning Type",
    typeStandard: "Standard",
    typeDeep: "Deep / Complete",
    vibeTitle: "Choose Your Home's Vibe",
    vibeSub: "How do you want your home to feel (and smell) after we leave?",
    vibe_fresh: "Fresh Linen",
    vibe_citrus: "Energizing Citrus",
    vibe_lavender: "Relaxing Lavender",
    vibe_eucalyptus: "Pure Eucalyptus",
    checklistTitle: "What's Included?",
    checklistSub: "Total transparency in every corner. We follow a 50-point premium checklist.",
    topOffer: "Special: 20% OFF Your First Deep Cleaning! Use code: LUMINA20",
    heroBadge: "Brazilian Owned & Operated",
    heroTitle: "A Clean Home, Pure Peace of Mind.",
    heroSub: "Experience the legendary Brazilian dedication to cleanliness. Premium residential and commercial services for our community in the USA.",
    getQuote: "Get a Free Quote",
    callNow: "Call Now",
    faqTitle: "Frequently Asked Questions",
    faqSub: "Everything you need to know about our services.",
    calcTitle: "Quick Estimate",
    calcSub: "Estimate the starting cost for your space.",
    estTotal: "Estimated starting at",
    bookNow: "Book Now",
    howItWorks: "How It Works",
    howSub: "Getting your space cleaned is easier than ever.",
    aboutTitle: "The Brazilian Touch",
    aboutSub: "In Brazil, cleaning is more than a chore; it's a culture of hospitality and meticulous care. We bring that same passion to every American home we serve.",
    statsHappy: "Happy Clients",
    statsClean: "Houses Cleaned",
    statsRating: "Average Rating",
    process1Title: "Book Online",
    process1Desc: "Select your preferred date and service type in seconds.",
    process2Title: "We Clean",
    process2Desc: "Our vetted professionals arrive and work their magic.",
    process3Title: "You Relax",
    process3Desc: "Come home to a spotless, fresh-smelling environment.",
    servicesTitle: "Our Premium Services",
    servicesSub: "We offer a range of professional cleaning solutions tailored to your specific needs.",
    reviewsTitle: "Loved by Your Neighbors",
    reviewsSub: "Join hundreds of happy families and businesses who trust Lumina.",
    contactTitle: "Request a Free Estimate",
    contactName: "Your Name",
    contactEmail: "Email Address",
    contactPhone: "Phone Number",
    contactMsg: "How can we help you?",
    contactSubmit: "Get My Quote",
    footerDesc: "Premium professional cleaning services. Brazilian quality serving the American community.",
    footerServices: "Services",
    footerNav: "Navigation",
    footerLegal: "Legal",
    copyright: "All rights reserved.",
    madeWith: "Made with",
    forOurComm: "for our community.",
    mapTitle: "Service Areas",
    mapSub: "Check if we serve your location",
    mapSearchPlaceholder: "Search city, zip, or state (e.g. Miami, FL)...",
    mapResults: "Search Results",
    mapNoResults: "No direct matches",
    mapStateServiced: "We service",
    mapStateServicedMsg: "While this city isn't on our standard list yet, we do operate in your state. Contact us to confirm!",
    mapNotServed: "Not Served Yet",
    mapNotServedMsg: "We haven't reached this region quite yet, but we're expanding fast!",
    mapInquire: "Inquire Now",
    mapRequest: "Request Expansion",
    mapAvailableRegions: "Available Regions",
    mapPrimaryCities: "Primary Cities",
    mapSelectedLocation: "Selected Location",
    mapConfirmation1: "Same-day booking available",
    mapConfirmation2: "Teams vetted and insured",
    calendarSelect: "Select a date in 'How it Works' above",
    calendarServiceDate: "Service Date",
    contactGlow: "Let's Get Your Space Glowing",
    office: "Office",
    whatsApp: "WhatsApp",
    nav_home: "Home",
    nav_services: "Services",
    nav_about: "About",
    nav_how: "How It Works",
    nav_reviews: "Reviews",
    nav_contact: "Contact",
    service_res_title: "Residential Cleaning",
    service_res_desc: "Keep your home spotless with our professional recurring or one-time cleaning service.",
    service_com_title: "Commercial Cleaning",
    service_com_desc: "A clean workplace is a productive one. We serve offices, clinics, and retail spaces.",
    service_deep_title: "Deep Cleaning",
    service_deep_desc: "A meticulous top-to-bottom clean for every corner of your property.",
    service_move_title: "Move In / Move Out",
    service_move_desc: "Make your transition stress-free with a professional deep clean before or after moving.",
    service_win_title: "Window Cleaning",
    service_win_desc: "Crystal clear views with our professional glass and window treatment services.",
    service_post_title: "Post-Construction",
    service_post_desc: "We remove debris, dust, and residues to make your newly renovated space livable.",
    check_vetted: "Vetted Professionals",
    check_eco: "Eco-Friendly Options",
    check_custom: "Custom Checklists",
    check_sameday: "Same Day Service",
    satisfactionBadge: "Satisfaction Guarantee",
    aboutTeamBadge: "About Our Team",
    desc_Florida: "Specializing in high-turnover vacation rental cleanings (Airbnb) and meticulous deep cleans for coastal properties.",
    desc_Massachusetts: "Focusing on the preservation of historic homes and high-demand move-in/out services for the local student community.",
    desc_New_Jersey: "Providing comprehensive office maintenance solutions and premium residential deep cleaning for suburban families.",
  },
  pt: {
    liveActivity: "Operações ao Vivo",
    liveMsg: "Equipes ativas na sua área",
    lastClean: "Último serviço finalizado",
    activeTeams: "Equipes Ativas",
    meetTeam: "Conheça os Especialistas",
    teamSub: "Por trás de cada limpeza Lumina está um profissional dedicado, treinado no padrão 'White-Glove' brasileiro.",
    exploreChecklist: "Padrão White-Glove",
    checklistDesc: "Selecione um cômodo para ver nosso protocolo de precisão de 50 pontos.",
    roomProtocol: "Protocolo por Cômodo",
    scrutinizedMsg: "Cada canto inspecionado pelo nosso supervisor líder.",
    // Equipe
    team_1_role: "Líder Sênior Pro", team_1_specialty: "Especialista em Hospitalidade", team_1_bio: "15 anos de experiência trazendo o alto padrão brasileiro para residências de luxo americanas.",
    team_2_role: "Especialista em Sanitização", team_2_specialty: "Limpeza Clínica", team_2_bio: "Obsessiva com detalhes. Ana garante que cada superfície esteja não apenas limpa, mas molecularmente pura.",
    team_3_role: "Artista da Organização", team_3_specialty: "Layout de Closet e Espaços", team_3_bio: "Beatriz acredita que a ordem na casa leva à ordem na mente. Seus toques finais são lendários.",
    // Itens do Checklist
    k_1: "Desengordurar coifa e fogão", k_2: "Polimento de aço inox", k_3: "Limpeza profunda de micro-ondas", k_4: "Detalhamento externo de armários", k_5: "Esfregação de rejuntes",
    b_1: "Remoção de depósitos minerais", b_2: "Polimento de espelhos sem marcas", b_3: "Sanitização de pontos de alto toque", b_4: "Lavagem manual do piso", b_5: "Descalcificação de box de vidro",
    be_1: "Arrumação de cama premium", be_2: "Limpeza de rodapés e sancas", be_3: "Detalhamento de grades de ventilação", be_4: "Aspiração sob a cama", be_5: "Revitalização de estofados",
    // UI
    estimatorTitle: "Calculadora de Orçamento",
    estimatorSub: "Configure seu espaço com precisão para uma estimativa instantânea.",
    bedrooms: "Quartos",
    suites: "Suítes",
    livingRooms: "Salas",
    kitchens: "Cozinhas",
    bathrooms: "Banheiros",
    pool: "Piscina",
    garden: "Jardim",
    sqft: "Área Total (m²)",
    cleaningType: "Tipo de Limpeza",
    typeStandard: "Padrão",
    typeDeep: "Pesada / Completa",
    vibeTitle: "Escolha a Vibe da sua Casa",
    vibeSub: "Como você quer que sua casa se sinta (e cheire) depois que sairmos?",
    vibe_fresh: "Algodão Fresco",
    vibe_citrus: "Cítrico Energizante",
    vibe_lavender: "Lavanda Relaxante",
    vibe_eucalyptus: "Eucalipto Puro",
    checklistTitle: "O que está incluído?",
    checklistSub: "Transparência total em cada canto. Seguimos um checklist premium de 50 pontos.",
    topOffer: "Especial: 20% OFF na sua primeira limpeza pesada! Use o código: LUMINA20",
    heroBadge: "Empresa de Brasileiros para o Mundo",
    heroTitle: "Casa Limpa, Mente em Paz.",
    heroSub: "Experimente a lendária dedicação brasileira à limpeza. Serviços premium residenciais e comerciais para nossa comunidade nos EUA.",
    getQuote: "Orçamento Grátis",
    callNow: "Ligar Agora",
    faqTitle: "Perguntas Frequentes",
    faqSub: "Tudo o que você precisa saber sobre nossos serviços.",
    calcTitle: "Estimativa Rápida",
    calcSub: "Calcule o valor inicial para o seu espaço.",
    estTotal: "Estimativa a partir de",
    bookNow: "Agendar Agora",
    howItWorks: "Como Funciona",
    howSub: "Limpar seu espaço nunca foi tão fácil.",
    aboutTitle: "O Toque Brasileiro",
    aboutSub: "No Brasil, limpeza é mais do que uma tarefa; é uma cultura de hospitalidade e cuidado meticuloso. Trazemos essa mesma paixão para cada casa americana que atendemos.",
    statsHappy: "Clientes Felizes",
    statsClean: "Casas Limpas",
    statsRating: "Avaliação Média",
    process1Title: "Agende Online",
    process1Desc: "Escolha sua data e tipo de serviço em segundos.",
    process2Title: "Nós Limpamos",
    process2Desc: "Nossos profissionais verificados chegam e fazem a mágica.",
    process3Title: "Você Relaxa",
    process3Desc: "Chegue em casa e encontre um ambiente impecável e cheiroso.",
    servicesTitle: "Nossos Serviços Premium",
    servicesSub: "Oferecemos uma gama de soluções de limpeza profissional adaptadas às suas necessidades específicas.",
    reviewsTitle: "Amado pelos seus Vizinhos",
    reviewsSub: "Junte-se a centenas de famílias e empresas felizes que confiam na Lumina.",
    contactTitle: "Solicite um Orçamento Grátis",
    contactName: "Seu Nome",
    contactEmail: "Endereço de E-mail",
    contactPhone: "Número de Telefone",
    contactMsg: "Como podemos ajudar?",
    contactSubmit: "Obter meu Orçamento",
    footerDesc: "Serviços de limpeza profissional premium. Qualidade brasileira servindo a comunidade americana.",
    footerServices: "Serviços",
    footerNav: "Navegação",
    footerLegal: "Jurídico",
    copyright: "Todos os direitos reservados.",
    madeWith: "Feito com",
    forOurComm: "para nossa comunidade.",
    mapTitle: "Áreas de Atendimento",
    mapSub: "Verifique se atendemos sua localização",
    mapSearchPlaceholder: "Buscar cidade, CEP ou estado (ex: Miami, FL)...",
    mapResults: "Resultados da Busca",
    mapNoResults: "Sem correspondências diretas",
    mapStateServiced: "Atendemos o estado de",
    mapStateServicedMsg: "Embora esta cidade ainda não esteja na lista, operamos em seu estado. Contate-nos para confirmar!",
    mapNotServed: "Ainda não Atendido",
    mapNotServedMsg: "Ainda não chegamos nesta região, mas estamos expandindo rápido!",
    mapInquire: "Consultar Agora",
    mapRequest: "Solicitar Expansão",
    mapAvailableRegions: "Regiões Disponíveis",
    mapPrimaryCities: "Cidades Principais",
    mapSelectedLocation: "Localização Selecionada",
    mapConfirmation1: "Agendamento para o mesmo dia disponível",
    mapConfirmation2: "Equipes verificadas e seguradas",
    calendarSelect: "Selecione uma data em 'Como Funciona' acima",
    calendarServiceDate: "Data do Serviço",
    contactGlow: "Vamos Deixar seu Espaço Brilhando",
    office: "Escritório",
    whatsApp: "WhatsApp",
    nav_home: "Início",
    nav_services: "Serviços",
    nav_about: "Sobre",
    nav_how: "Como Funciona",
    nav_reviews: "Avaliações",
    nav_contact: "Contato",
    service_res_title: "Limpeza Residencial",
    service_res_desc: "Mantenha sua casa impecável com nosso serviço profissional de limpeza recursiva ou pontual.",
    service_com_title: "Limpeza Comercial",
    service_com_desc: "Um local de trabalho limpo é produtivo. Atendemos escritórios, clínicas e espaços comerciais.",
    service_deep_title: "Limpeza Pesada (Deep)",
    service_deep_desc: "Uma limpeza meticulosa de cima a baixo para cada canto da sua propriedade.",
    service_move_title: "Mudanças (Move In/Out)",
    service_move_desc: "Torne sua transição livre de estresse com uma limpeza profunda antes ou depois de mudar.",
    service_win_title: "Limpeza de Janelas",
    service_win_desc: "Vistas cristalinas com nossos serviços profissionais de tratamento de vidros e janelas.",
    service_post_title: "Pós-Obra",
    service_post_desc: "Removemos detritos, poeira e resíduos para tornar seu espaço recém-renovado habitável.",
    check_vetted: "Profissionais Verificados",
    check_eco: "Produtos Ecológicos",
    check_custom: "Checklists Personalizados",
    check_sameday: "Serviço no Mesmo Dia",
    satisfactionBadge: "Garantia de Satisfação",
    aboutTeamBadge: "Sobre Nossa Equipe",
    desc_Florida: "Especializados em limpeza de aluguel de temporada (Airbnb) e limpezas profundas detalhadas para propriedades costeiras.",
    desc_Massachusetts: "Foco na preservação de casas históricas e serviços de mudança (move-in/out) para a comunidade estudantil local.",
    desc_New_Jersey: "Oferecendo soluções completas de manutenção de escritórios e limpeza residencial pesada premium para famílias suburbanas.",
  }
};
